var Code={
    Attribute:{
        ALL:'ATR.ALL',
        STR:'ATR.STR',
        DEX:'ATR.DEX',
        CON:'ATR.CON',
        INT:'ATR.INT',
        WIS:'ATR.WIS',
        CHA:'ATR.CHA',
        WIL:'ATR.WIL',
        LUK:'ATR.LUK'
    },
    Resource:{
        HEALTH:'RES.HEALTH',
        MANA:'RES.HEALTH',
        SPIRIT:'RES.SPIRIT',
        STAMINA:'RES.STAMINA'        
    }
};
